status = ${sys:LOG4J_STATUS:-warn}
name = ConsoleConfig

# Define the appender
appender.console.type = Console
appender.console.name = STDOUT
appender.console.layout.type = PatternLayout
# Ensure the pattern is on a SINGLE line with no trailing spaces
#property.appenderPattern=${sys:loggerPattern:-%msg%n}
appender.console.layout.pattern = ${sys:loggerPattern:-%msg%n}

# Define the root logger
rootLogger.level = info
rootLogger.appenderRef.stdout.ref = STDOUT